#!/system/bin/sh
#
# 
#


#setprop ;
htc.audio.lpa.a2dp=0
htc.audio.global.state=0
htc.audio.global.profile=0
htc.audio.q6.topology=0
htc.audio.enable_dmic=1
#export for SoundHound
persist.htc.audio.pcm.samplerate=44100
persist.htc.audio.pcm.channels=2

# System props for audio
persist.audio.fluence.mode=endfire
persist.audio.vr.enable=false
persist.audio.handset.mic=analog

htc.audio.swalt.enable=1
htc.audio.swalt.mingain=14512
htc.audio.alc.enable=1
